### ISSUE TITLE
Naming Issues

### ISSUE THREAD

**Issue by PaulC91** [RobWHickman/sf.dotdensity#1]
Hi Rob,

Thanks a lot for making this package! It's something I always thought I should do myself but I've never got round to diving into the R package development world.

I just wanted to point out a couple of things that could make the use case for the package clearer:

- typo on chloropleth ~ choropleth*
- I'm by no means a cartography expert but I don't think describing these maps as "dot choropleths" is accurate. All the literature I've seen on them describes them as dot-density maps, or in this case multivariate dot-density maps, and often discuss the differences of "dot-density v. choropleth". So I think the current name of the package may lead to some confusion!

Thanks again for making the package and let me know if you're looking for any contributions for further development.

Paul.

**Comment by RobWHickman** [comment]
crap- only just seen this (I only put it together as a quick and non-serious thing). I'll get on fixing both of those mistakes :)

Any further development of course welcome although it might well be that the idea has moved on in the year in between!
